### PR TITLE
Update iteration.py

### PR DESCRIPTION
**Pull request by yirsung**
Adding the following  iteration methods.
-inearmixing
-excitingmixing

### CODE REVIEW

**Comment by chrisconlon** [comment]
Can you benchmark them?

**Comment by yirsung** [comment]
Dear Chris:

Sure, should I use the included BLP automobile data and model to do it?

Best,
Richeng

**Comment by jeffgortmaker** [comment]
Sure, making sure they are fine on the automobile or fake cereal data would be nice. Also at a minimum can you make sure they work in the [tests](https://github.com/jeffgortmaker/pyblp/blob/master/tests/test_iteration.py)? Also see [this page](https://pyblp.readthedocs.io/en/stable/testing.html).

Is the motivation for adding these to fill in the gaps of what scipy supports? That's fine I guess. Although it's probably the case that I didn't add these because something about how they worked didn't play nice with the unit tests.

**Comment by jeffgortmaker** [comment]
I'm still getting some errors when including these additional methods in the unit test, so I'm going to close this PR for now. But if you can figure out how to make them work, feel free to keep commenting / re-open!

**Pull request closed without merging**
